function [fitresult, gof] = createFit(angle, max_E)
%CREATEFIT(ANGLE,MAX_E)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : angle
%      Y Output: max_E
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Jun-2019 13:26:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( angle, max_E );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'max_E vs. angle', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel angle
ylabel max_E
grid on


